ServerPort = 8999
ServerName = "gate"
ServerId = 1
MaxConn = 1000
SendBuffLength = 2000

[LogConfig]
Level = -1

[RedisConfig]
Addr = "139.196.78.71:6379"
DB = 0
Pwd = "com.1234"

[DbConfig]
Dns = "kim118000:com.1234@tcp(139.196.78.71:3306)/game_sys?charset=utf8mb4&parseTime=true"
MaxConnNumber = 20
IdleConnNumber = 10