// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: messageId.proto

package id

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageId int32

const (
	// 客户端发送的消息
	MessageId_NONE MessageId = 0 //无
	// request
	MessageId_TO_SERVER_LOGIN MessageId = 1
	// response
	MessageId_TO_CLIENT_LOGIN MessageId = 10001
)

// Enum value maps for MessageId.
var (
	MessageId_name = map[int32]string{
		0:     "NONE",
		1:     "TO_SERVER_LOGIN",
		10001: "TO_CLIENT_LOGIN",
	}
	MessageId_value = map[string]int32{
		"NONE":            0,
		"TO_SERVER_LOGIN": 1,
		"TO_CLIENT_LOGIN": 10001,
	}
)

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}

func (x MessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_messageId_proto_enumTypes[0].Descriptor()
}

func (MessageId) Type() protoreflect.EnumType {
	return &file_messageId_proto_enumTypes[0]
}

func (x MessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageId.Descriptor instead.
func (MessageId) EnumDescriptor() ([]byte, []int) {
	return file_messageId_proto_rawDescGZIP(), []int{0}
}

var File_messageId_proto protoreflect.FileDescriptor

var file_messageId_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x40, 0x0a, 0x09, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x4f, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x0f, 0x54, 0x4f, 0x5f, 0x43, 0x4c,
	0x49, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x91, 0x4e, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6d, 0x31,
	0x31, 0x38, 0x30, 0x30, 0x30, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x64, 0x3b, 0x69,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageId_proto_rawDescOnce sync.Once
	file_messageId_proto_rawDescData = file_messageId_proto_rawDesc
)

func file_messageId_proto_rawDescGZIP() []byte {
	file_messageId_proto_rawDescOnce.Do(func() {
		file_messageId_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageId_proto_rawDescData)
	})
	return file_messageId_proto_rawDescData
}

var file_messageId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messageId_proto_goTypes = []interface{}{
	(MessageId)(0), // 0: protocol.MessageId
}
var file_messageId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageId_proto_init() }
func file_messageId_proto_init() {
	if File_messageId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageId_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageId_proto_goTypes,
		DependencyIndexes: file_messageId_proto_depIdxs,
		EnumInfos:         file_messageId_proto_enumTypes,
	}.Build()
	File_messageId_proto = out.File
	file_messageId_proto_rawDesc = nil
	file_messageId_proto_goTypes = nil
	file_messageId_proto_depIdxs = nil
}
